### ISSUE TITLE
Rules not validating on editor

### ISSUE THREAD

**Issue by maccth** [UoYCS-plasma/GP2-editor#63]
Hello, I have a created a valid rule and checked it using `gp2 -r` however when I attempt to run a program that uses it the logs show `Attempting to validate Rules.`.

The message in the editor is `Could not start validating one of the rules`.

What would you recommend?

**Comment by GrahamCampbell** [comment]
Could you provide the rule here, and I'll see if I can mimic the behaviour, or see why the rule might not be valid?

**Comment by maccth** [comment]
```
add
(
a, b : int;
x, y, z : char
)
[<150,188>
    | (n0, x <64.5, 68.5> )
      (n1, y <105.329029868802, 156.163850237403> )
      (n2, z <146.204977877886, 68.8586386082753> )
    | (e0, n0, n1, a)
      (e1, n1, n2, b)
]
=>
[<149,169>
    | (n0, x <143.89072685597, 137.687398984073> )
      (n1, y <103.945363427985, 68.5> )
      (n2, z <64, 137.687398984073> )
    | (e0, n0, n2, a+b)
      (e1, n0, n1, a)
      (e2, n1, n2, b)
]
interface = 
{
n0, n1, n2
}
```

Cheers!

**Comment by GrahamCampbell** [comment]
If it helps, there is a Dockerized "interpreter" available for GP2 (that runs the compiler and then executes the output on the program) available at https://gitlab.com/YorkCS/Batman/GP2I. (GitLab login required, but the repo is not "private", so you should be able to access it) There's also a web interface you can self-host using Docker Compose: https://gitlab.com/YorkCS/Batman/GP2I-HTTP. There are some details in Appendix A at https://www.cs.york.ac.uk/plasma/publications/pdf/CampbellRomoPlump.EPSRC.18.pdf.

---

Running a program with your rule and an empty input graph indicated the syntax was valid:

```bash
Grahams-MacBook-Pro-2:~ graham$ docker run -v ${PWD}:/data registry.gitlab.com/yorkcs/batman/gp2i test graph
No output graph: rule Main_add not applicable.
```

---

In fact to get the web interpreter, just put this file by itself in a folder (don't even need to clone the repo): https://gitlab.com/YorkCS/Batman/GP2I-HTTP/blob/master/docker-compose.yml, and then run `docker-compose up`, then visit localhost in your browser. Example (Figure 5.9 from the PDF):

![image](https://user-images.githubusercontent.com/2829600/48582327-2130c300-e91c-11e8-88b6-d2b9d14276e2.png)

**Comment by maccth** [comment]
Cheers, that's really helpful. I was doing some research on graph programming languages and GP2 came up in a few papers. It looked really interesting.

**Comment by GrahamCampbell** [comment]
GP2 is particularly good because of it's formal semantics being expressed with classical (labelled) graph transformation theory, and the language itself being very small. Other languages like grgen are perhaps more practically useful, however do not have the elegant foundation or such a small language.

Section 3 and Appendix A of Bak's PHD Thesis gives an account of GP2's syntax and semantics: http://etheses.whiterose.ac.uk/12586/7/Thesis.pdf. Plump has a set of slides from 8th International School on Rewriting 2015: https://www-users.cs.york.ac.uk/~det/isr15-handout.pdf that introduces the language.

The standard text for graph rewriting theory is https://www.springer.com/gb/book/9783540311874, however it doesn't make for a great text for a beginner I'm afraid. A more general text on term rewriting (and abstract rewriting systems) is https://www21.in.tum.de/~nipkow/TRaAT/, which is beginner friendly.

**Comment by maccth** [comment]
Thanks for all the information, Graham!

**Comment by maccth** [comment]
My mistake, I had misspecified the compiler location in the CMakeLists.
